feat : header 회원가입 컴포넌트 이동 추가
tacku-table/tacku-table pull request #69
Opened 2023-02-22 15:22 UTC by JH-anfseo

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
feat/recipe-Detail-page -> dev

### 변경 사항
헤더에 회원가입 페이지 추가했습니다.

2023-02-22 15:24 UTC, be-brain approved these changes
good

2023-02-22 18:18 UTC, be-brain requested changes
레시피상세페이지 카테고리명에 &들어간것 /로 변경해주세요~!!

2023-02-23 01:07 UTC, be-brain approved these changes
ggood

2023-02-23 01:09 UTC, ddoqi approved these changes
고생하셨습니다!!!

2023-02-23 01:37 UTC, merged